name: flutter_stripe_project
description: "Flutter Stripe"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_stripe: ^10.1.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/
    - .env

